# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cai < Formula
  desc ""
  homepage "https://github.com/TomByte/commit-ai"
  version "1.0.4"

  on_macos do
    url "https://github.com/TomByte/commit-ai/releases/download/v1.0.4/commit-ai_1.0.4_darwin_all.tar.gz"
    sha256 "85e7b6ee57059bfd3300241dd54afd73d82b61dc7844a23b0678a0a91f9a2063"

    def install
      bin.install "commit-ai"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TomByte/commit-ai/releases/download/v1.0.4/commit-ai_1.0.4_linux_amd64.tar.gz"
      sha256 "3ce6a858e8f1a45e1e2fd5d0f0280a4af23c8632af6bb2b543af19768120ee92"

      def install
        bin.install "cai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomByte/commit-ai/releases/download/v1.0.4/commit-ai_1.0.4_linux_arm64.tar.gz"
      sha256 "7262a8318c91aa625a8ef9cab26ba943a0e0b954c59b42fa012d69aad8a0e37a"

      def install
        bin.install "cai"
      end
    end
  end
end
